{% set version = "2.0.0" %}

package:
  name: jdatetime
  version: {{ version }}

source:
  fn: jdatetime-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jdatetime/jdatetime-{{ version }}.tar.gz
  sha256: 7facd437d27365e217787e1013ecdc402aa77af7248e16128f6a753920000905

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - jdatetime

about:
  home: https://github.com/slashmili/python-jalali
  license: PSF
  summary: 'Jalali datetime binding for python'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
