travis:
  secure:
    BINSTAR_TOKEN: ia7U/kLobLG/ZrUaHnwc+QNnz7lfJn4HyFs9mDRYoz4k3gTTJJxYdvWRs+sW+myJfomNsnFV8lP3g3EfLWO6l+71o+OQ5mHDActChCX6zSvzr3ZYE5R+45rCAepGAsQ0KW/v1GJ08aR5p0Tf8J7JkMrFtNH0ZpAt35KfQuIgc1ufHp8Ud51VrZd/BIOIRgBjvuC5VxRr7roNNS50QtwYS6Mem6S9/QLMORBa8Ugg/nCks3ZlZ0+5bxjvvGHDha6+yV+ux3DaD9WkBVMaRP0PaPj7eYqUJ9GWXIVDlahiryEzF0EJNUvTJLXMIUewxZsw1YViVOiiMjkgjfeS3hUpKY2yGMuX+ZunkJU6/nwXc6JqjPB8jiafExqboq5OpgrG5dDibdjRtwQTQQVQvGP5IilnOcw0drsydPBxyZiImYwNn01sH7Ljupyj3wPbLfg5wW7MH7HEllPpgjbGWB2ZB/uFlVLK86hNQE34aYBSxURBNUa5jDsqDNxhSfNorpZU3FKIx0dDrTRynkl1EuaCNz2xaruKwxs8dcscW1+w33crt1Bs/7lmCLUqS29Ec+YOkKkahw2yD7rO8t5Sv+vamTPY4T67Ybng4YBfYSLK4x3qkNS/e3zc3bWvlMFU0BEc/EFxwDBnI8wbVDRRCtmtJYjp+pNNe39LKpWHdH0EVCs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
